### ISSUE TITLE
Refactor exec_cfg_check.R

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubValidations#148]
As we now have hubs that are using custom functions, this is a good opportunity to refactor the `exec_cfg_check.R` file a bit. I ran into difficulty working with this in #142 partially because the file has a lot of abbreviations and no explanatory comments.

I would like to refactor this to add some explanatory comments and refactor some parts to avoid repetition and use boolean sentinel variables. For example, we could refactor this: 

https://github.com/hubverse-org/hubValidations/blob/5c8395297181e2a2cd1f73661155511278d48438/R/exec_cfg_check.R#L36-L42

to use sentinel variables and comments

```r
get_caller_env_formals <- function(fn, caller_env, cfg_args) {
  # find the arguments of the custom function
  fn_arg_names <- rlang::fn_fmls_names(fn)
  # variables available from the calling environment (e.g. hub_path, tbl, etc...)
  available_vars <- rlang::env_names(caller_env)
  # match the arguments from the calling environment, discarding the ones not needed
  args_from_vars <- fn_arg_names %in% available_vars
  # do not include arguments that are specified in the config. 
  not_config_args <- !fn_arg_names %in% names(cfg_args)
  caller_env_fmls <- fn_arg_names[args_from_vars & not_config_args]
  # extract these values from the calling environment, replacing with `NULL` if they are missing.
  rlang::env_get_list(caller_env, nms = caller_env_fmls, default = NULL)
}
```

I would be happy to tackle this.

**Comment by annakrystalli** [comment]
Looking at the origin function I think a comment would be enough to explain what's going on though as it's not really that complicated

**Comment by zkamvar** [comment]
> Looking at the origin function, wouldn't a comment be enough to explain what's going on though as it doesn't seem that complicated?

When I was reading it initially, it took me a while to understand that this was including the variables from the calling environment, but without the variables specified in the config. If I'm trying to debug this function, having the sentinel boolean variables helps me unpack what's going on quicker.

**Comment by annakrystalli** [comment]
Ok. Feel free to refactor
