### ISSUE TITLE
Re-export functions useful to modelers from `hubUtils` and `hubData`

### ISSUE THREAD

**Issue by annakrystalli** [hubverse-org/hubValidations#149]
In a [recent PR in hubDocs](https://github.com/hubverse-org/hubDocs/pull/197) on model output data addressed heavily towards modelers, a number of useful functions were suggested which were spread over 3 different packages:

- `hubUtils::read_config()`
- `hubData::create_hub_schema()` and `hubData::coerce_to_hub_schema()`
- `hubValidations::submission_tmpl()`

While there's good reason for the original functions to be spread out across these packages, I feel `hubValidations` is really the package with modelers as a key target and therefore should contain any functions required for their workflows.  As such, I propose we re-export the above functions from other packages into `hubValidations` so they are available to modelers through this package.

`hubUtils` and `hubData` are already imports to `hubValidations` so it should be an easy fix.

**Comment by zkamvar** [comment]
I think this is a good idea and will implement.
