### ISSUE TITLE
add `exact = TRUE` or reduce expected classes for `expect_s3_class()`

### ISSUE THREAD

**Issue by zkamvar** [hubverse-org/hubValidations#180]
We have a lot of tests that use [`testthat::expect_s3_class()`](https://testthat.r-lib.org/reference/inheritance-expectations.html) to test that a hub check is what we expect.

For example:

https://github.com/hubverse-org/hubValidations/blob/c21383e115e73fb3ea57c3951f2031117b7ad121/tests/testthat/test-check_file_n.R#L14-L20

In this test, we are assuming that the check will fail if the output of `check_file_n()` does not have the classes `c("check_failure", "hub_check", "rlang_error", "error", "condition")`. However, the problem is that [the default expectation of `inherits()` is that this class inherits from _any_ of these classes](https://hachyderm.io/@zkamvar/113640496107401312), which means that **it's possible to have a situation where we have a `"check_success"` and `expect_s3_class()` for a `"check_failure"` would not fail.** I illustrate the consequences here: 

``` r
library(testthat)
class <- c("success", "check")
failure_expected <- c("failure", "check")
x <- structure("", class = class)
print(expect_s3_class(x, failure_expected)) # Passes, even though `x` is a "success" and we are testing for a "failure"
#> [1] ""
#> attr(,"class")
#> [1] "success" "check"
show_failure(expect_s3_class(x, failure_expected, exact = TRUE)) # Fails, as expected
#> Failed expectation:
#> `x` has class 'success'/'check', not 'failure'/'check'.
```

<sup>Created on 2024-12-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by zkamvar** [comment]
I've been going through and changing these and I already found a condition in which this has returned a silent false-positive. In https://github.com/hubverse-org/hubValidations/commit/8c2d46dc6f82ae26725784e356b9d793890167c7, we downgraded a missing metadata file to a `check_failure` instead of a `check_error`.

However, this check passes because both of the checks inherit from "rlang_error", "error", and "condition"

https://github.com/hubverse-org/hubValidations/blob/6dcf5bf11f6fcbb06992ffddcc83afff2ddb1201/tests/testthat/test-check_submission_metadata_file_exists.R#L18-L24

**Comment by zkamvar** [comment]
I found an old test that is having a different sort of problem: 

https://github.com/hubverse-org/hubValidations/blame/6dcf5bf11f6fcbb06992ffddcc83afff2ddb1201/tests/testthat/test-check_tbl_values_required.R#L162-L183

It returns a "check_failure" because the output type IDs for quantiles do not match. 

``` r
    library("hubValidations")
    hub_path <- "~/Documents/Git/hubverse-org/PKGS/hubValidations/tests/testthat/testdata/hub-it"
    file_path <- "Tm-Md/2023-11-04-Tm-Md.csv"
    round_id <- "2023-11-04"
    tbl <- read_model_out_file(
      file_path = file_path,
      hub_path = hub_path,
      coerce_types = "chr"
    )
    chk <- check_tbl_values_required(
      tbl = tbl,
      round_id = round_id,
      file_path = file_path,
      hub_path = hub_path
    )
    waldo::compare(tbl$output_type_id, chk$missing$output_type_id, max_diffs = 20)
#>      old     | new                    
#>  [1] "0.010" - "0.01" [1]             
#>  [2] "0.025" - "0.05" [2]             
#>  [3] "0.050" - "0.1"  [3]             
#>  [4] "0.100" - "0.15" [4]             
#>  [5] "0.150" - "0.2"  [5]             
#>  [6] "0.200" - "0.25" [6]             
#>  [7] "0.250" - "0.3"  [7]             
#>  [8] "0.300" - "0.35" [8]             
#>  [9] "0.350" - "0.4"  [9]             
#> [10] "0.400" - "0.45" [10]            
#> [11] "0.450" - "0.5"  [11]            
#> [12] "0.500" - "0.55" [12]            
#> [13] "0.550" - "0.6"  [13]            
#> [14] "0.600" - "0.65" [14]            
#> [15] "0.650" - "0.7"  [15]            
#> [16] "0.700" - "0.75" [16]            
#> [17] "0.750" - "0.8"  [17]            
#> [18] "0.800" - "0.85" [18]            
#> [19] "0.850" - "0.9"  [19]            
#> [20] "0.900" - "0.95" [20]            
#>  ... ...       ...    and 268 more ...
```

<sup>Created on 2024-12-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


I'm going to add an explicit skip to this until we can figure out what the correct solution for this is. The justification for adding an explicit skip instead of deleting this is because this test was written for a specific reason last year, but something has changed about the conditions. The explicit skip will highlight this for future work that is out of scope for this particular task.

**Comment by annakrystalli** [comment]
Good spot! That's an erroneous test file actually as the quantile output type IDs have trailing zeros which we do not allow (so the check correctly fails). If the trailing zeros are removed though that test should pass.

**Comment by annakrystalli** [comment]
Thinking about it, before overwriting it's probably good to check it's not a deliberate error that's being used for another test though!

**Comment by zkamvar** [comment]
> Thinking about it, before overwriting it's probably good to check it's not a deliberate error that's being used for another test though!

This is why I'm adding a `skip()` instead. The check is already effectively skipped, this just makes it explicit.

**Comment by annakrystalli** [comment]
> This is why I'm adding a skip() instead. The check is already effectively skipped, this just makes it explicit.

Sure but what I mean is if we create another file with the correct output type IDs and redirect the skipped test to that file it should pass and therefore not need to be skipped.
