### ISSUE TITLE
Add validations for sample output_type data

### ISSUE THREAD

**Issue by nickreich** [hubverse-org/hubValidations#80]
There is a laundry list of validations [here](https://docs.google.com/document/d/1vJT8Uw8fQgoY5sajcokZSfnF7M89eiiiwlRXVkCuj2k/edit#heading=h.qli9sktijlj4).

**Comment by annakrystalli** [comment]
# Sample validation tests

- [ ] Validate all value combinations valid (as part of `check_tbl_values()`)
- [ ] Validate all required value combinations submitted (as part of `check_tbl_values_required()`)
- [ ] Validate correct number of samples submitted.
- [ ] Validate that samples within a submission file contain the same combination of optional values across all samples
- [ ] Validate that samples conform to sample dependence defined by the compound task id set configuration.
