### ISSUE TITLE
Validation fails matching output_type_id types

### ISSUE THREAD

**Issue by M-7th** [hubverse-org/hubValidations#94]
Hi, 
first of all, thanks for all the effort that has been put into this v 3.0.0 release! This was really helpful.

We are finalising the new ECDC Scenario Hub and we are facing a strange issue trying to validate samples.
We are submitting a parquet file with output_type set to "sample" and output_type_id configured as integer and populated with values ranging from 1 to 300. 
When submitting, the validation fails with the following error:
```
The validation checks produced some failures/errors reported above.
Backtrace:
    ▆
 1. └─hubValidations::check_for_errors(v, verbose = TRUE)
 2.   └─rlang::abort("\nThe validation checks produced some failures/errors reported above.")
Execution halted
Notice: ! 2024_2025_1_FLU-ISI-TestModel2.parquet: Column data types do not match hub
  schema.  `output_type_id ` should be "double " not "integer "

```
If we change output_type_id type in the Parquet file to Double, with values from 1.0 to 300.0, the validation is successful.
Is there something we are missining/doing wrong in the configuration?

Thanks as always for your precious help!
P.

This is how we configured the samples output_type in the tasks.json:
```
"output_type": {
      "sample": {
          "output_type_id_params": {
              "is_required": true,
              "type": "integer",
              "min_samples_per_task": 1,
              "max_samples_per_task": 100,
              "compound_taskid_set": ["round_id", "scenario_id", "target", "location", "pop_group"]
          },
          "value":{
              "type": "double",
              "minimum": 0
          }
      }
   }
```
This is the parquet schema for the output_type_id as integer:
```
{
    "PrimitiveType": {
      "field_info": {
        "name": "output_type_id",
        "repetition": "Optional",
        "id": null
      },
      "logical_type": null,
      "converted_type": null,
      "physical_type": "Int64"
    }
  }
```
and here is the parquet schema for the output_type_id as double
```
{
    "PrimitiveType": {
      "field_info": {
        "name": "output_type_id",
        "repetition": "Optional",
        "id": null
      },
      "logical_type": null,
      "converted_type": null,
      "physical_type": "Double"
    }
}
```

**Comment by annakrystalli** [comment]
Hi @M-7th, 

Are you collecting any other output types that have a "double" output type Id? This is what it sounds like the issue is and it results from needing have a single common data type for the output type Id column across the whole hub, especially for parquet files, otherwise opening all files as an arrow dataset would fail.

**Comment by annakrystalli** [comment]
Admittedly this is not well documented but we have plans to address that here https://github.com/hubverse-org/hubDocs/issues/143

**Comment by M-7th** [comment]
Hi @annakrystalli,
sorry for the late response, but I've been on leave last week.
Yes, currently we are collecting, in addition to the samples, also quantiles.
Do you think there is a way  to handle such a scenario? 
I did a quick test having both samples and quantiles as double in the parquet file and, with the above mentioned tasks.json, the validation was successful. but I'm not sure if this would be an acceptable solution.
Thanks for the support

**Comment by annakrystalli** [comment]
FYI @M-7th here are a couple of issues to monitor for fixes regarding this issue:
- https://github.com/hubverse-org/hubValidations/issues/91
- https://github.com/hubverse-org/schemas/issues/87

And more generally, the issues in this view: https://github.com/orgs/hubverse-org/projects/3/views/12

**Comment by annakrystalli** [comment]
Hello @M-7th !

Just wanted to let you know, all required changes have been made for you to be able to fix the output type id column data type to character.

I still need to write a section in hubDocs with the details (https://github.com/hubverse-org/hubDocs/issues/143) but if you upgrade your `hubValidations` and `hubData` packages as well as your schema version in your configs to `v3.0.1` you can set the output type id column to character by setting the `output_type_id_datatype` property, e.g.: 

```json
{
  "schema_version": "https://raw.githubusercontent.com/hubverse-org/schemas/main/v3.0.1/tasks-schema.json",
  "rounds": [...],
  "output_type_id_datatype": "character"
}
```

There some detail in this issue that could help and will form the basis of the hubDocs section.

Let me know how that goes and if you need any help!

**Comment by M-7th** [comment]
Thank you very much @annakrystalli for your precious and very quick help!!
